# Generated by Django 2.1.15 on 2020-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('fqdn', models.CharField(max_length=50)),
                ('ipAddress', models.CharField(max_length=50)),
                ('portNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
