# Generated by Django 2.1.15 on 2020-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='Plex', max_length=50),
            preserve_default=False,
        ),
    ]
