# Generated by Django 3.0.6 on 2020-05-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_config_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='enable',
        ),
    ]
