# Generated by Django 3.0.6 on 2020-05-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_config_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ssl',
            field=models.BooleanField(default=False),
        ),
    ]
