# Generated by Django 3.0.6 on 2020-05-05 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_config_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='sslexpire',
            field=models.DateTimeField(default='1970-01-01'),
        ),
        migrations.AddField(
            model_name='config',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
