# Generated by Django 3.0.6 on 2020-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200505_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='sslexpire',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
