# Generated by Django 3.0.6 on 2020-05-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='config',
            name='updated_at',
        ),
    ]
